all 3 covariates:

$`CML estimates`
     1      2      3      4
base 0 -1.268  0.383  2.231
1    0 -0.396 -0.540 -0.406
2    0  0.023  0.028  0.009
3    0  0.070 -0.779 -0.703

$`standard errors`
      1     2     3     4
base NA 0.886 0.932 1.134
1    NA 0.256 0.273 0.324
2    NA 0.020 0.020 0.025
3    NA 0.255 0.273 0.328

$`Z statistics`
      1      2      3      4
base NA -1.431  0.411  1.967
1    NA -1.545 -1.983 -1.253
2    NA  1.160  1.345  0.366
3    NA  0.274 -2.852 -2.142

$`two-sided p values`
      1     2     3     4
base NA 0.153 0.681 0.049
1    NA 0.122 0.047 0.210
2    NA 0.246 0.179 0.715
3    NA 0.784 0.004 0.032

$`log likelihood`
[1] -535.5944

$tests
                      test statistic df p value
likelihood ratio test         19.173  9   0.024
gradient test                 19.375  9   0.022
Rao score test                18.979  9   0.025
Wald test                     18.583  9   0.029

$`information criteria`
          AIC      BIC
[1,] 1089.189 1126.506


Parameter-free Rao score Test

RS = 19.095
p value = 0.022



covariates gender and age only

$`CML estimates`
     1      2      3      4
base 0 -1.229 -0.097  1.801
1    0 -0.385 -0.463 -0.347
2    0  0.023  0.028  0.009

$`standard errors`
      1     2     3     4
base NA 0.875 0.905 1.104
1    NA 0.256 0.269 0.322
2    NA 0.020 0.020 0.024

$`Z statistics`
      1      2      3      4
base NA -1.404 -0.107  1.631
1    NA -1.506 -1.723 -1.076
2    NA  1.157  1.388  0.380

$`two-sided p values`
      1     2     3     4
base NA 0.160 0.915 0.103
1    NA 0.132 0.085 0.282
2    NA 0.247 0.165 0.704

$`log likelihood`
[1] -542.309

$tests
                      test statistic df p value
likelihood ratio test          5.744  6   0.452
gradient test                  5.762  6   0.450
Rao score test                 5.728  6   0.454
Wald test                      5.691  6   0.459

$`information criteria`
          AIC      BIC
[1,] 1096.618 1121.496



covariate gender only

$`CML estimates`
     1      2      3      4
base 0 -0.239  1.134  2.193
1    0 -0.365 -0.436 -0.327

$`standard errors`
      1     2     3     4
base NA 0.179 0.193 0.229
1    NA 0.255 0.268 0.321

$`Z statistics`
      1      2      3      4
base NA -1.334  5.889  9.583
1    NA -1.435 -1.631 -1.021

$`two-sided p values`
      1     2     3     4
base NA 0.182 0.000 0.000
1    NA 0.151 0.103 0.307

$`log likelihood`
[1] -543.5253

$tests
                      test statistic df p value
likelihood ratio test          3.312  3   0.346
gradient test                  3.315  3   0.346
Rao score test                 3.309  3   0.346
Wald test                      3.302  3   0.347

$`information criteria`
          AIC     BIC
[1,] 1093.051 1105.49




covariate age only

$`CML estimates`
     1      2      3     4
base 0 -1.338 -0.217 1.715
1    0  0.021  0.025 0.007

$`standard errors`
      1     2     3     4
base NA 0.871 0.901 1.096
1    NA 0.019 0.020 0.024

$`Z statistics`
      1      2      3     4
base NA -1.537 -0.241 1.564
1    NA  1.066  1.265 0.297

$`two-sided p values`
      1     2     3     4
base NA 0.124 0.809 0.118
1    NA 0.287 0.206 0.766

$`log likelihood`
[1] -544.1447

$tests
                      test statistic df p value
likelihood ratio test          2.073  3   0.557
gradient test                  2.077  3   0.557
Rao score test                 2.068  3   0.558
Wald test                      2.063  3   0.559

$`information criteria`
          AIC      BIC
[1,] 1094.289 1106.728



covariate treatment only

$`CML estimates`
     1      2      3      4
base 0 -0.463  1.309  2.395
1    0  0.082 -0.742 -0.671

$`standard errors`
      1     2     3     4
base NA 0.181 0.201 0.248
1    NA 0.254 0.271 0.326

$`Z statistics`
      1      2      3      4
base NA -2.561  6.512  9.645
1    NA  0.323 -2.737 -2.058

$`two-sided p values`
      1     2     3    4
base NA 0.010 0.000 0.00
1    NA 0.747 0.006 0.04

$`log likelihood`
[1] -538.8569

$tests
                      test statistic df p value
likelihood ratio test         12.649  3   0.005
gradient test                 12.742  3   0.005
Rao score test                12.559  3   0.006
Wald test                     12.370  3   0.006

$`information criteria`
          AIC      BIC
[1,] 1083.714 1096.153






 